/**
 * The Bot -> Vibe-agent-profile projection (#445, ADR-0027). PURE: a Bot record
 * in, the exact text of the two files out. No fs, no ids minted, no clock — the
 * writer (`write-bot-profile.ts`) is the only thing that touches disk.
 *
 * The record is the SOURCE OF TRUTH; these files are a projection of it we
 * rewrite freely, which is why both carry a generated-file header. A Bot's
 * persona lives in the `.md` because compaction always preserves system
 * messages (probe #421) — an instruction that rides in the system prompt cannot
 * drift, however long the conversation runs.
 *
 * Shapes verified on the wire at vibe-acp 2.24.1 (`docs/acp-capture.md` §14):
 *
 * - `~/.vibe/agents/<profileId>.toml` becomes a selectable ACP mode whose `id`
 *   is the FILE STEM, `name` is `display_name`, `description` is `description`.
 * - `system_prompt_id` is the BARE STEM of a `.md` in `~/.vibe/prompts/` —
 *   Vibe appends the extension itself, so it is never a path and never carries
 *   `.md`.
 * - `agent_type` must stay `agent`: a `subagent` profile is filtered out of
 *   `availableModes` with no wire signal at all.
 */

/** The generated-file marker both files carry, verbatim (ADR-0027). */
export const BOT_PROFILE_HEADER =
  'Generated by Vibe Mistro — edits will be overwritten; change this Bot in the app.'

/**
 * The safety posture every Bot profile is written with. `neutral` is Vibe's own
 * default (`AgentProfile.from_toml`) and matches the `ask` builtin: tool
 * executions still need approval, so creating a Bot can never quietly widen what
 * an agent is allowed to do. Approval posture is Mode's job, not a Bot's.
 */
export const BOT_PROFILE_SAFETY = 'neutral'

/** The Bot fields the projection reads. A subset of `BotRecord`, so tests need no row. */
export interface BotProfileSource {
  profileId: string
  name: string
  description: string
  instructions: string
}

/** The rendered projection: two file names and their exact contents. */
export interface BotProfileFiles {
  profileId: string
  /** File name inside the user agents dir (`~/.vibe/agents/`). */
  agentFileName: string
  /** File name inside the user prompts dir (`~/.vibe/prompts/`). */
  promptFileName: string
  /** The complete profile TOML. */
  agentToml: string
  /** The complete system-prompt Markdown. */
  promptMarkdown: string
}

/** Render a Bot's two profile files. Pure — validate the result before writing it. */
export function projectBotProfile(source: BotProfileSource): BotProfileFiles {
  return {
    profileId: source.profileId,
    agentFileName: `${source.profileId}.toml`,
    promptFileName: `${source.profileId}.md`,
    agentToml: renderBotProfileToml(source),
    promptMarkdown: renderBotPromptMarkdown(source),
  }
}

/**
 * The profile TOML. Every key here is on `VIBE_AGENT_PROFILE_KEYS` and is
 * checked by `validateBotProfileFiles` before a byte reaches disk — Vibe
 * silently ignores anything it does not recognise (#424), so a typo would
 * produce a profile that loads, "works", and quietly lacks the setting.
 *
 * `system_prompt_id` is the profile id itself: one id names the Bot, its TOML,
 * its prompt `.md` and its ACP mode, so there is nothing to keep in sync.
 */
export function renderBotProfileToml(source: BotProfileSource): string {
  return [
    `# ${BOT_PROFILE_HEADER}`,
    `display_name = ${tomlString(source.name.trim())}`,
    `description = ${tomlString(source.description.trim())}`,
    `agent_type = "agent"`,
    `safety = "${BOT_PROFILE_SAFETY}"`,
    `system_prompt_id = ${tomlString(source.profileId)}`,
    '',
  ].join('\n')
}

/**
 * The system prompt. The header is an HTML comment so it stays invisible in
 * every Markdown renderer while still marking the file as generated. The name
 * heading is what tells the model who it is; the description and the
 * instructions follow verbatim, and empty sections are dropped rather than
 * emitted as blank noise the model has to read past.
 */
export function renderBotPromptMarkdown(source: BotProfileSource): string {
  const sections = [`<!-- ${BOT_PROFILE_HEADER} -->`, `# ${source.name.trim()}`]
  const description = source.description.trim()
  if (description) sections.push(description)
  const instructions = source.instructions.trim()
  if (instructions) sections.push(instructions)
  return `${sections.join('\n\n')}\n`
}

/**
 * A TOML basic string. Vibe parses these with `tomllib`, which rejects the whole
 * file on a malformed one — and a file that fails to parse is dropped WITHOUT
 * any wire signal, so escaping is load-bearing rather than cosmetic.
 */
export function tomlString(value: string): string {
  let out = '"'
  for (const char of value) {
    switch (char) {
      case '\\':
        out += '\\\\'
        break
      case '"':
        out += '\\"'
        break
      case '\n':
        out += '\\n'
        break
      case '\r':
        out += '\\r'
        break
      case '\t':
        out += '\\t'
        break
      default: {
        const code = char.codePointAt(0) ?? 0
        // The control ranges TOML requires escaped (and DEL, for tidiness).
        out += code < 0x20 || code === 0x7f ? `\\u${code.toString(16).padStart(4, '0')}` : char
      }
    }
  }
  return `${out}"`
}
